---
- hosts: localhost
  gather_facts: no
  vars_files:
    - controller_setup.yml
    - user_settings.yml

  vars:
    controller_validate_certs: false
    controller_configuration_async_delay: 5

  tasks:
    - name: Setup Components
      include_role:
        name: "redhat_cop.controller_configuration.{{ item }}"
      loop: "{{ controller_components }}"
      when:
        - controller_components | d("") | length > 0

